# Generated by Django 4.1.1 on 2022-11-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['date_joined', 'is_author']},
        ),
    ]
